### ISSUE TITLE
Populate current message in input, if set

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-admin-plugin#4]
If there is already a banner message set and being displayed, then it would be helpful to preload that text in the admin page (`message` input). E.g. you spot a typo and want to correct it, you have to retype the entire message again, with current implementation.

**Comment by nickdos** [comment]
code reviewed ✅

Can't test functionality yet - trying to find an app in test env that includes the changes.

**Comment by ansell** [comment]
Moving this to "Waiting" on the board until it is deployed into a test application, then feel free to move it back to QA on the board.

**Comment by nickdos** [comment]
QA testing passed. Moving to Done.
