### ISSUE TITLE
Build Info is missing explicit path

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/ala-admin-plugin#8]
Unless the app hosting this plugin provides a path for build info, the build info controller is inaccessible.

**Comment by nickdos** [comment]
code reviewed ✅

**Comment by ansell** [comment]
Has this been deployed into a test environment? Moving to Waiting column on the project board until it has and this is ready for QA.

**Comment by nickdos** [comment]
QA with latest version `2.3-SNAPSHOT` was all good (using `ala-hub` as test app). Moving to done.
